eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8901
spring:
  application:
    name: service-feign
#Enable circuit breaker for application
feign:
  hystrix:
    enabled: true
