eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          #uri: https://git.oschina.net/chrywhy/test
          #searchPaths: spring-cloud/helloworldConfig
          uri: https://github.com/michael-mx/halbet
          searchPaths: config_client/spring_cloud_test
  application:
    name: config-server
